- name: Get certificate via certbot for nginx
  shell: |
      certbot certonly --nginx --noninteractive --agree-tos \
      --email {{ cert_email }} -d {{ domain }}
  when: host_type == "public"
  tags:
    - ubuntu
    - build
    - certbot